<<<<<<< HEAD
# Generated by Django 2.1.3 on 2018-11-18 17:36

from django.conf import settings
=======
# Generated by Django 2.1.2 on 2018-11-18 12:30

>>>>>>> bd2d19d04ede1d8c5073154ab9835069c8f58b0b
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_con_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=120)),
                ('date_conference', models.DateTimeField(auto_now_add=True)),
                ('conference_link', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='video_request',
            fields=[
                ('date_requested', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('request_id', models.CharField(max_length=12)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requester', models.CharField(max_length=120)),
>>>>>>> bd2d19d04ede1d8c5073154ab9835069c8f58b0b
            ],
        ),
    ]
