# Generated by Django 2.1.2 on 2018-10-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('force', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='userlog',
            fields=[
                ('userlogid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equationlog',
            name='userlogid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='force.userlog'),
        ),
    ]
