# Generated by Django 2.1.2 on 2018-11-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0003_auto_20181015_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('age', models.FloatField()),
                ('dob', models.DateField(null=True)),
                ('email', models.CharField(max_length=150)),
                ('contact_number', models.BigIntegerField()),
                ('street_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='equationlog',
            name='userlogid',
        ),
        migrations.DeleteModel(
            name='equationLog',
        ),
        migrations.DeleteModel(
            name='userlog',
        ),
    ]
