# Generated by Django 2.1.2 on 2018-11-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0006_auto_20181110_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='age',
            field=models.IntegerField(),
        ),
    ]
