# Generated by Django 2.1.2 on 2018-11-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0007_auto_20181110_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='fullname',
            new_name='name',
        ),
    ]
