# Generated by Django 2.1.2 on 2018-11-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
