# Generated by Django 2.1.2 on 2018-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0011_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
                ('contact_number', models.BigIntegerField()),
                ('specialisations', models.CharField(max_length=500)),
            ],
        ),
    ]
