# Generated by Django 2.1.2 on 2018-11-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0012_user_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appointment',
            name='doctor',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
