# Generated by Django 2.1.2 on 2018-11-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0013_user_appointment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='street_address',
            new_name='address',
        ),
    ]
