# Generated by Django 2.1.3 on 2018-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0014_auto_20181117_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
