# Generated by Django 2.1.2 on 2018-12-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_profile', '0002_user_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_appointment',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='username',
        ),
    ]
