# Generated by Django 2.1.2 on 2018-12-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_profile', '0003_auto_20181202_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='name',
        ),
    ]
