# Generated by Django 2.1.2 on 2018-12-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_profile', '0004_remove_user_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
