# Generated by Django 2.1.2 on 2018-12-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userlog',
        ),
    ]
