# Generated by Django 2.1.2 on 2018-12-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_delete_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
