# Generated by Django 2.1.3 on 2018-11-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20181114_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
