# Generated by Django 2.1.3 on 2018-11-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_purchaseitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
