# Generated by Django 2.1.3 on 2018-11-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_auto_20181116_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
