# Generated by Django 2.1.3 on 2018-11-16 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('med', '0006_purchaseitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='user',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
