# Generated by Django 2.1.3 on 2018-11-16 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0007_auto_20181116_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
