# Generated by Django 2.1.3 on 2018-11-16 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('med', '0008_auto_20181116_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='user',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
