# Generated by Django 2.1.3 on 2018-11-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0010_auto_20181116_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='0000000', max_length=15),
        ),
    ]
