# Generated by Django 2.1.3 on 2018-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0015_auto_20181116_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
