# Generated by Django 2.1.3 on 2018-11-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0018_auto_20181117_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.Medicine', unique=None),
        ),
    ]
