# Generated by Django 2.1.3 on 2018-11-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0019_auto_20181117_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='ref_code',
        ),
    ]
