# Generated by Django 2.1.3 on 2018-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0020_remove_purchaseitem_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='ref_code',
            field=models.CharField(default='0000000', max_length=15),
        ),
    ]
