# Generated by Django 2.1.2 on 2018-11-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0021_purchaseitem_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
        migrations.AddField(
            model_name='medicine',
            name='about',
            field=models.CharField(default='0000000', max_length=1000),
        ),
    ]
