# Generated by Django 2.1.3 on 2018-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_affiliation',
            name='doc_name',
            field=models.ManyToManyField(default='', to='docapp.Doctor'),
        ),
    ]
