# Generated by Django 2.1.3 on 2018-11-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office_docavailability',
            name='slot1',
        ),
    ]
