# Generated by Django 2.1.2 on 2018-12-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_review',
            name='client_accountid',
        ),
        migrations.RemoveField(
            model_name='user_review',
            name='doc_id',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='User_Review',
        ),
    ]
