# Generated by Django 2.1.3 on 2018-11-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_remove_office_docavailability_slot1'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_docavailability',
            name='slot1',
            field=models.TimeField(default='9:00'),
        ),
    ]
