# Generated by Django 2.1.3 on 2018-11-17 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_auto_20181118_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='office_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docapp.Office'),
        ),
    ]
