# Generated by Django 2.1.2 on 2018-12-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_auto_20181202_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='office_id',
        ),
        migrations.DeleteModel(
            name='Appointment_Status',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='hospital_affiliation',
            name='doc_name',
        ),
        migrations.RemoveField(
            model_name='labappointment',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='tests_available',
        ),
        migrations.RemoveField(
            model_name='office',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='office',
            name='hosp_affiliation_id',
        ),
        migrations.RemoveField(
            model_name='office_docavailability',
            name='office_id',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='doc_name',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Hospital_Affiliation',
        ),
        migrations.DeleteModel(
            name='labAppointment',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Office_Docavailability',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Tests_info',
        ),
    ]
