<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-11-18 09:50
=======
# Generated by Django 2.1.3 on 2018-11-18 10:05
>>>>>>> 8f6213fd2e1d7b8d99508cbca9a54eac57701f8c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0003_auto_20181118_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docapp.LabTest'),
        ),
    ]
