# Generated by Django 2.1.3 on 2018-11-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0004_auto_20181116_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_docavailability',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
