# Generated by Django 2.1.3 on 2018-11-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0005_auto_20181118_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labappointment',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docapp.Tests_info'),
        ),
    ]
