# Generated by Django 2.1.3 on 2018-11-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0005_office_docavailability_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_docavailability',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
