# Generated by Django 2.1.3 on 2018-11-18 13:48

from django.db import migrations, models
import docapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0006_auto_20181118_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labappointment',
            name='lab_id',
            field=models.CharField(max_length=150, verbose_name=docapp.models.LabTest),
        ),
    ]
