# Generated by Django 2.1.3 on 2018-11-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0007_auto_20181118_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labappointment',
            name='lab_id',
        ),
    ]
