<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-12-11 17:12
=======
# Generated by Django 2.1.3 on 2018-12-11 17:33
>>>>>>> 7806a00e60afe21bbca1dfa8765961cc86629602

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('roomname', models.TextField()),
>>>>>>> 7806a00e60afe21bbca1dfa8765961cc86629602
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patientdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('symptoms', models.CharField(max_length=250)),
                ('Department', models.CharField(max_length=250)),
            ],
        ),
    ]
