# Generated by Django 2.1.3 on 2018-11-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_patientdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='patient',
        ),
    ]
