# Generated by Django 2.1.3 on 2018-12-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_advertisements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default='AdvertisementImages/None/no-img.jpg', upload_to='AdvertisementsImages/'),
        ),
    ]
