# Generated by Django 2.1.2 on 2018-12-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
    ]
