# Generated by Django 2.1.3 on 2018-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='spec',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
