# Generated by Django 2.1.2 on 2018-12-11 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181212_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 0, 29, 12, 840274)),
        ),
    ]
