# Generated by Django 2.1.2 on 2018-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181208_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
