# Generated by Django 2.1.3 on 2018-11-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181126_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='office_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='home.Doctor'),
            preserve_default=False,
        ),
    ]
