# Generated by Django 2.1.3 on 2018-12-11 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181211_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 23, 57, 3, 43290)),
        ),
    ]
