# Generated by Django 2.1.2 on 2018-12-11 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181211_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='client_accountid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 14, 53, 42, 282609)),
        ),
    ]
