# Generated by Django 2.1.3 on 2018-12-11 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181211_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 16, 52, 54, 690934)),
        ),
    ]
