# Generated by Django 2.1.2 on 2018-12-11 14:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181211_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_add',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='0000000', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='home.Medicine'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='client_accountid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 20, 22, 33, 6001)),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
