# Generated by Django 2.1.3 on 2018-12-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181126_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=60)),
                ('goal_amount', models.FloatField()),
                ('beneficiary_name', models.CharField(max_length=50)),
                ('beneficiary_relation', models.CharField(max_length=25)),
                ('Fundraiser_story', models.TextField()),
                ('End_date', models.DateField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user_profile')),
            ],
        ),
    ]
