# Generated by Django 2.1.2 on 2018-12-02 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20181126_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
