# Generated by Django 2.1.2 on 2018-12-11 19:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181212_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reports',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 0, 54, 16, 494676)),
        ),
    ]
