# Generated by Django 2.1.2 on 2018-12-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_add',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
