# Generated by Django 2.1.2 on 2018-12-07 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_fundraiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pharmacy', models.CharField(max_length=100)),
                ('about', models.CharField(default='0000000', max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('mfg_date', models.DateField(null=True)),
                ('exp_date', models.DateField(null=True)),
                ('pres_req', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(default='0000000', max_length=15)),
                ('quantity', models.IntegerField(null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(null=True)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Medicine', unique=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='0000000', max_length=100)),
                ('last_name', models.CharField(default='0000000', max_length=100)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='', max_length=200)),
                ('interests', models.CharField(blank=True, max_length=255)),
                ('medicine', models.ManyToManyField(blank=True, to='home.Medicine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='home.PurchaseItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.UserProfile'),
        ),
    ]
