# Generated by Django 2.1.2 on 2018-12-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181207_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
