# Generated by Django 2.1.3 on 2018-12-11 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181211_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 18, 52, 28, 730466)),
        ),
    ]
