# Generated by Django 2.1.2 on 2018-12-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181212_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reports',
            name='file',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 0, 57, 32, 912171)),
        ),
    ]
