# Generated by Django 2.1.2 on 2018-12-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181207_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email_id',
        ),
    ]
