# Generated by Django 2.1.2 on 2018-12-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_doctor_email_id'),
        ('home', '0006_auto_20181207_1615'),
    ]

    operations = [
    ]
