# Generated by Django 2.1.2 on 2018-12-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20181208_1634'),
        ('home', '0007_auto_20181206_2244'),
    ]

    operations = [
    ]
