# Generated by Django 2.1.2 on 2018-12-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_otp_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='office',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='office',
            name='hosp_affiliation_id',
        ),
        migrations.RemoveField(
            model_name='office_docavailability',
            name='office_id',
        ),
        migrations.RemoveField(
            model_name='hospital_affiliation',
            name='hosp_photo',
        ),
        migrations.AlterField(
            model_name='hospital_affiliation',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_affiliation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_affiliation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_affiliation',
            name='doc_name',
            field=models.ManyToManyField(blank=True, default='', null=True, to='home.Doctor'),
        ),
        migrations.AlterField(
            model_name='hospital_affiliation',
            name='hosp_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_affiliation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='doc_name',
            field=models.ManyToManyField(blank=True, null=True, to='home.Doctor'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institute_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='procurement_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qual_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Office_Docavailability',
        ),
        migrations.AddField(
            model_name='clinic',
            name='hosp_affiliation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Hospital_Affiliation'),
        ),
    ]
