# Generated by Django 2.1.2 on 2018-12-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_apoint_ment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoint_ment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='apoint_ment',
            name='username',
        ),
        migrations.DeleteModel(
            name='Apoint_ment',
        ),
    ]
