# Generated by Django 2.1.2 on 2018-12-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181208_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_review',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
