# Generated by Django 2.1.2 on 2018-12-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181210_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='hosp_affiliation_id',
        ),
        migrations.RemoveField(
            model_name='hospital_affiliation',
            name='doc_name',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='doc_name',
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Hospital_Affiliation',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
